theme = "ayu_evolve"

[editor]
line-number = "relative"
# clipboard.copy = "wl-copy"
# clipboard.paste = "wl-paste"

# bufferline = "multiple"
# mouse = true
# auto-info = false

[editor.lsp]
# display-messages = true
# display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]


