
[[language]]
name = "rust"
# auto-format = false

[language-server.rust-analyzer.config]
cachePriming.enable = true
diagnostics.experimental.enable = true

[[language]]
name = "python"
auto-format = true


[[language]]
name = "cpp"
auto-format = true

[[language]]
name = "ocaml"
formatter = { command = "ocamlformat", args = ["-", "--impl", "--enable-outside-detected-project"] }
auto-format = true
